# Hexo Configuration
## Docs: http://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Apollo Community
subtitle: Information about the Apollo Community
description:

versions:
  - '1'
sidebar_categories:
  null:
    - index
    - contributing
    - code-of-conduct
    - graphql-events
    - apollo-mission-briefing
github_repo: apollostack/community
content_root: source

social_links:
  github: 'https://github.com/apollostack'
  twitter: '@apollostack'

# API keys
apis:
  segment: wgrIo8Bul0Ujl8USETG3DB6hONdy4kTg
  gtm: GTM-PNFDVBB

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://www.apollographql.com/docs/community/
root: /docs/community/
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public/docs/community
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Extensions
## Plugins: http://hexo.io/plugins/
## Themes: http://hexo.io/themes/
theme: meteor
